#############################################
# Initialize /Users/hamadu/.brewfile/Brewfile
#############################################


# tap repositories and their packages

tap caskroom/cask
cask alfred
cask aquaterm
cask atom
cask coteditor
cask docker
cask firefox
cask flip4mac
cask google-chrome
cask google-japanese-ime
cask intellij-idea
cask iterm2
cask java
cask minecraft
cask mysqlworkbench
cask skitch
cask slack
cask steam
cask vagrant-manager
cask vagrant
cask virtualbox
cask xquartz

tap homebrew/bundle

tap homebrew/core
brew veclibfort
brew jpeg
brew qscintilla2
brew gd
brew htop
brew mysql
brew nodebrew
brew gdbm
brew libsndfile
brew wrk
brew fontconfig
brew gmp
brew freetype
brew python
brew tbb
brew python3
brew ghostscript
brew qt
brew libyaml
brew fftw
brew szip
brew libvorbis
brew ruby-build
brew pkg-config
brew qhull
brew go
brew webp
brew redis
brew lua
brew libpng
brew memcached
brew imagemagick
brew jq
brew suite-sparse
brew portaudio
brew octave
brew wget
brew hdf5
brew arpack
brew openssl
brew utf8proc
brew isl
brew libtool
brew libtiff
brew tmux
brew xz
brew qrupdate
brew pcre
brew libssh2
brew pyenv
brew glpk
brew fzf
brew libmpc
brew flac
brew libevent
brew pstoedit
brew peco
brew gl2ps
brew fig2dev
brew autoconf
brew zsh
brew rust
brew sqlite
brew plotutils
brew ansible
brew curl
brew epstool
brew gcc
brew sip
brew cmake
brew fltk
brew gnuplot --with-aquaterm --with-x11 --with-qt
brew pyqt
brew direnv
brew tig
brew mas
brew little-cms2
brew graphicsmagick
brew libogg
brew openssl@1.1
brew oniguruma
brew readline
brew metis
brew rbenv
brew mpfr

tap homebrew/science

tap homebrew/services

tap homebrew/versions

tap homebrew/x11

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 409183694 Keynote (7.2)
appstore 539883307 LINE (5.3.0)
appstore 421739418 MIDITrail (1.2.3)
appstore 409203825 Numbers (4.2)
appstore 409201541 Pages (6.2)
appstore 497799835 Xcode (8.3.3)
